"""Adicionando coluna mensagem

Revision ID: 9dda7a83786b
Revises: 3c2a3fc05814
Create Date: 2024-11-22 12:13:10.291862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dda7a83786b'
down_revision = '3c2a3fc05814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mensagem', sa.String(), nullable=True))
        batch_op.drop_column('mesagem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mesagem', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('mensagem')

    # ### end Alembic commands ###
